### ISSUE TITLE
Review of my lib

### ISSUE THREAD

**Issue by determin1st** [davidbegin/python-in-the-morning#18]
Hello man, would you like to review my lib?

First of all, if you agree, I like to ask you to *not to browse* my profile or my repos because it's easy to find the topic. The main point here, is to collect first observation. Does it have any improvements? How are they expressed by the reader? Does it necessary at all? Another lib for a lib?

As it's a review from developer's point of view, you should know the basics of `javascript` and web stuff. How to plug a lib and use it for something. Reviewing the code is not necessary, only usage analysis, comparison with other tools and alike. The topic is:

#### Ajax vs Fetch, ways to make an HTTP request from the browser

You may look through these links:

https://github.com/axios/axios
https://github.com/sindresorhus/ky
https://twitter.com/sindresorhus/status/1037763588826398720?lang=en
https://visionmedia.github.io/superagent/
https://danlevy.net/you-may-not-need-axios/
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
https://fetch.spec.whatwg.org/
https://github.com/whatwg/fetch/issues/601

So, i'm sorry to bother you with all of this, but it's based on pure interest.
You may start the topic and i will drop a link to the repo to review, as i tried initially.

Again, that's only if you agree. It doesn't really matter what result you report - positive or negative, both are okay, long review or short, both are okay.

**Comment by davidbegin** [comment]
Hello!

So I am little confused by your request. My guess is you are asking me to look at the current landscape of tools for ajax versus fetch, like axios and other fetch implementations, and see if there is a space for a tool you are building.

Please correct me if I am wrong!

You also said don't look at your projects, but c'mon you know that makes me want to look more!

So what I would say, is I am not to familiar with the current fetch/ajax happenings (although my work just did switch from fetch to axios, but I was not involved!) . I could review the library from the standpoint I do of any library, and see how well you sell me in this competitive landscape, if that;s what you want!

Also I will be doing a joint stream on Saturday at 10AM PST with someone who is actually intimately familiar with this area, and could provide more informed convo.

**Comment by determin1st** [comment]
> Please correct me if I am wrong!

Nope, you are right!

> You also said don't look at your projects, but c'mon you know that makes me want to look more!

Oke, it's here: https://github.com/determin1st/httpFetch
I'm not sure if im been writing a good manual how to use it.. 

> I could review the library from the standpoint I do of any library, and see how well you sell me in this competitive landscape, if that;s what you want!

Great, deal!

> Also I will be doing a joint stream on Saturday at 10AM PST with someone who is actually intimately familiar with this area, and could provide more informed convo.

Oke, I'll try to be there man!

**Comment by davidbegin** [comment]
So not sure we helped any, but I learned some things and have fun. Curious to hear updates on the project, and how it evolves :skier:

**Comment by determin1st** [comment]
Im happy with your review. Pointed out some problems and issues to work on.
Thanks a lot man.
