### ISSUE TITLE
self driving car code review, thoughts?

### ISSUE THREAD

**Issue by tscheer100** [davidbegin/python-in-the-morning#23]
this can fit on either wednesday, thursday, or friday. IDK if you've heard of comma.ai but it's pretty sick and I looked at the code and saw it was written in PYTHON :O 

https://github.com/commaai/openpilot

https://comma.ai/

https://www.youtube.com/watch?v=3Y67XKPmtY8

**Comment by davidbegin** [comment]
Ha yeah, I'm a git geohot fan! Although I think I'll barely be able to understand this code!

**Comment by davidbegin** [comment]
While I love Geohot, I'm going to stick to viewer code review for now. But will keep this in mind, if I start moving into AI!
