### ISSUE TITLE
How should I structure this code in a better way

### ISSUE THREAD

**Issue by skywalk1411** [davidbegin/python-in-the-morning#24]
I'm a junior programmer javascript, been learning for around a month now, I asked a review before from Strager, I got comments and I have applied the comments and it was very useful, strager a beast, but I was told my way of coding isn't conventional, there are better ways to structure such code I am practicing with. I am an amateur but I am improving... I was told ...

so I built this node.js code that receive data from a websocket, interpret it and take decision based on a decisionTable and actionTable according to the websocket data trends...

I am not asking how to optimize how my decision are taken, just how should I structure such type of code...

the file in the attachment is the complete code.
[index.txt](https://github.com/davidbegin/python-in-the-morning/files/4293789/index.txt)

**Comment by davidbegin** [comment]
Hopefully we were able to help some on stream, or at least have fun :smile: 
Learning to structure projects is different based on a lot of factors, and often hotly debated, so it's a life long learning and you're on your way!
