### ISSUE TITLE
gray code generator

### ISSUE THREAD

**Issue by Frank-Buss** [davidbegin/python-in-the-morning#29]
I hacked a program in a few minutes to generate gray codes, was a task at https://leetcode.com: https://repl.it/repls/BigheartedUtilizedEyestrain
strager said it is gross, but stream was at end, couldn't ask him so far why :-)

**Comment by davidbegin** [comment]
Curious to hear what you end up changing!

**Comment by Frank-Buss** [comment]
I could asked Strager yesterday and he said only the tobin function was gross, and I agreed, was just a quick debug hack. He said the rest was ok, but he doesn't like recursions in general. I didn't change anything so far. So I closed this issue, not really worth a review for you on stream, unless you want to discuss gray codes or try it yourself. There is a much much more optimized version at Wikipedia: https://en.wikipedia.org/wiki/Gray_code#Converting_to_and_from_Gray_code
